"""Paket 1.4 — stage I/O from inside the container.

The orchestrator's CODE_STAGE is mounted into the container as a filesystem
volume. This writes a generated-code file to <mount>/<task_id>/<iter>/, reads it
back, and prints markers + a directory listing so the job log is verifiable.
Persistence to the actual Snowflake stage is checked separately from the laptop.

Env: MOUNT_PATH (default /workspace), TASK_ID, ITERATION.
"""
import os
import sys

MOUNT = os.environ.get("MOUNT_PATH", "/workspace")
TASK_ID = os.environ.get("TASK_ID", "task-demo")
ITER = os.environ.get("ITERATION", "0")

CONTENT = "# generated by orchestrator\ndef solution():\n    return 'STAGE OK'\n"


def main() -> int:
    target_dir = os.path.join(MOUNT, TASK_ID, ITER)
    path = os.path.join(target_dir, "solution.py")
    try:
        os.makedirs(target_dir, exist_ok=True)
        with open(path, "w") as fh:
            fh.write(CONTENT)
        with open(path) as fh:
            read_back = fh.read()
        listing = sorted(os.listdir(target_dir))
    except Exception as exc:  # noqa: BLE001
        print(f"STAGE_IO_FAIL: {type(exc).__name__}: {exc}", flush=True)
        return 1

    ok = read_back == CONTENT
    print("STAGE_IO_BEGIN", flush=True)
    print(f"wrote: {path}", flush=True)
    print(f"listing: {listing}", flush=True)
    print(f"roundtrip_ok: {ok}", flush=True)
    print("STAGE_IO_END", flush=True)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
